on: [push]
name: CI
jobs:
  runsml:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Debian packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y mlton make

      - name: Install MLton
        run: |
          curl -O https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117-1.amd64-linux-glibc2.31.tgz
          tar xf mlton-20210117-1.amd64-linux-glibc2.31.tgz
          make -C mlton-20210117-1.amd64-linux-glibc2.31 install PREFIX=$HOME/.local
          rm -rf mlton-20210117-1.amd64-linux-glibc2.31*

      - uses: diku-dk/install-mlkit@v1.0.0
      - uses: diku-dk/install-futhark@v1.1.0

      - name: Check
        run: |
          mlkit --version
          smlpkg --version

      - run: |
          make run_test
